### PR TITLE
Merge ExecutionContext and ExecutionState.

### PR DESCRIPTION
**Pull request by zherczeg**
State without Context is rare, and the merged structure consumes less amount of memory.

### CODE REVIEW

**Comment by yichoi** [comment]
@zherczeg please rebase this PR with current master.

**Comment by zherczeg** [comment]
Thank you for the heads up. Rebase is done.

**Comment by clover2123** [comment]
@zherczeg Would you please rebase this patch again? Other looks nice to me:)

**Comment by zherczeg** [comment]
Thank you for the reviews. Rebase is done.

**Comment by zherczeg** [comment]
@ksh8281 @clover2123 could you land this patch?

**Comment by clover2123** [comment]
@zherczeg Sorry for late. It took some time for setting the new repo.

**Pull request merged**
